fix(cli): fix export failed error on export command
resend/react-email pull request #1214
Opened 2024-01-20 13:59 UTC by AnnatarHe

fix the cli error like this:

```bash
TypeError: component.default is not a function
    at /Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:778:75
    at step (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:186:23)
    at Object.next (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:127:20)
    at asyncGeneratorStep (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:12:28)
    at _next (/Users/app/mailbox/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:30:17)
```

<img width="1151" alt="image" src="https://github.com/resend/react-email/assets/8704175/f132bb6e-ba95-4060-9e0e-7bd0685ea1e8">

reproduce:

```bash
npx create-email
pnpm i
# rename the tailwind import
npm run export
```

2024-01-22 11:47 UTC, gabrielmfern requested changes

2024-01-22 11:47 UTC, gabrielmfern commented on packages/react-email/src/cli/commands/export.ts
> +      const rendered = render(component.default.default({}), options);
Replace the import with a require and I think this will remove the need to do `.default.default`

2024-01-23 09:48 UTC, gabrielmfern approved these changes

2024-01-24 17:53 UTC, AnnatarHe commented
Hi @gabrielmfern , thanks for your change.

what should I do now? I just want to use the CLI to build my email project 😂

2024-01-24 18:25 UTC, gabrielmfern commented
@AnnatarHe Just wait out for a bit until @bukinoshita can review it, I can't approve it anymore since I made changes 😆

2024-01-25 14:28 UTC, tim3w4rp commented
Nice. Thank you @gabrielmfern.

@bukinoshita Any update on this? Sorry for pushing you like this but it's blocking me at work. Otherwise, I'd have to either go the separate repo route or use an alternative.

2024-01-26 15:39 UTC, gabrielmfern commented
@tim3w4rp You can always use a patch to not be blocked.

2024-02-02 01:53 UTC, lightstrike commented
@gabrielmfern Waiting for this to be merged as well to incorporate into a project using Resend. Is there a recommended patching approach in the meantime? I tried the `yarn add 'AnnatarHe/react-email#canary/packages/react-email'` approach through [GitPkg](https://gitpkg.vercel.app/) but it didn't work as expected.

2024-02-02 05:55 UTC, kdoroszewicz commented
> @gabrielmfern Waiting for this to be merged as well to incorporate into a project using Resend. Is there a recommended patching approach in the meantime? I tried the `yarn add 'AnnatarHe/react-email#canary/packages/react-email'` approach through [GitPkg](https://gitpkg.vercel.app/) but it didn't work as expected.

You can use patch-package utility to do this. I cloned this repo, installed dependencies, applied changes from this PR and then rebuilt the library to get proper bundles with changes from this PR.  Once you have the file (index.js) you can place it in you projects node_modules and then run patch-package like described in it's readme.

2024-02-04 00:15 UTC, vcapretz approved these changes

2024-02-04 12:22 UTC, merged